name: Bug Report
description: Report incorrect answers, outdated info, or errors
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us maintain accurate interview content!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What issue did you find?
      placeholder: Describe the problem...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Which question/answer?
      placeholder: |
        - Category: iOS Memory Management
        - Question: What is ARC?
        - Section: Answer
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Incorrect Answer
        - Outdated Information
        - Code Doesn't Work
        - Typo/Grammar
        - Missing Information
        - Broken Link
    validations:
      required: true

  - type: textarea
    id: correct
    attributes:
      label: Correct Information
      description: What should it say?
      placeholder: The correct answer is...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have verified my correction
          required: true
