name: Feature Request
description: Suggest new questions or improvements
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have questions to add? We'd love to include them!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to add?
      placeholder: Describe your suggestion...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Question(s)
        - New Category
        - Better Answer
        - Code Example
        - Structure Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - iOS
        - Android
        - Cross-Platform
        - General
    validations:
      required: true

  - type: dropdown
    id: level
    attributes:
      label: Difficulty Level
      options:
        - Junior
        - Mid-Level
        - Senior
        - Lead/Principal
        - All Levels
    validations:
      required: true

  - type: textarea
    id: questions
    attributes:
      label: Proposed Questions
      description: If adding questions, list them
      placeholder: |
        1. Question about X
        2. Question about Y
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I can help write answers
          required: false
